Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Musical_Instrument_Store.Data.Interfaces;
using Musical_Instrument_Store.Data.Models;
using Musical_Instrument_Store.ViewModels;

namespace Musical_Instrument_Store.Controllers
{
    public class CartController : Controller
    {
        private readonly IMusicalInstrumentService _musicalInstrumentService;
        private readonly ICartService _cartService;
        private Cart _cart;
        public CartController(IMusicalInstrumentService musicalInstrumentService, ICartService cartService, Cart cart)
        {
            _musicalInstrumentService = musicalInstrumentService;
            _cartService = cartService;
            _cart = cart;
        }

        public async Task<IActionResult> Index()
        {
            
            var elements = await _cartService.GetCartLines(_cart);
            _cart.cartLines = elements;

            var obj = new CartViewModel { cartViewModel = _cart };

            return View(obj);
        }
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            var item = await _musicalInstrumentService.GetMIbyIdAsync(id);
            if (item != null)
            {
                TempData["AlertMessage"] = "Успішно додано!";
                await _cartService.AddToCartAsync(item, _cart);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCartLine(int cartlineId)
        {
            try
            {
                TempData["AlertMessage"] = "Успішно видалено!";
                await _cartService.DeleteCartLineAsync(cartlineId);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Musical_Instrument_Store.Data.Models;
using Musical_Instrument_Store.ViewModels;

namespace Musical_Instrument_Store.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    TempData["AlertMessage"] = "Роль успішно додано!";
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                TempData["AlertMessage"] = "Роль успішно видалено!";
            }

            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRolesViewModel model = new ChangeRolesViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                
                var userRoles = await _userManager.GetRolesAsync(user);
                
                var allRoles = _roleManager.Roles.ToList();
                
                var addedRoles = roles.Except(userRoles);
                
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/style-loader.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style-sidebar.css" rel="stylesheet" type="text/css">
    <link href="~/css/MusicalInstrument/musicalinstrumentlist.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/lib/template/vendors/mdi/css/materialdesignicons.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">


</head>
<body>
    <div class="loader">
        <div></div>
    </div>
   
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper" class="shadow-sm">
            <ul class="sidebar-nav dropdown">
                <li class="sidebar-brand mb-5 ">
                    <a asp-controller="Home" asp-action="Index"> <img src="~/img/MainImg/Logo.png" alt="Mentor's Musical Store" width="160" height="105" /></a>

                </li>
                <hr class="m-4">
                <li>
                    <a class="effect-underline" asp-controller="MusicalInstrument" asp-action="Index"><i class="mdi mdi-folder-multiple"></i>     Каталог</a>
                </li>
                <li>
                    <a class="effect-underline" asp-controller="Cart" asp-action="Index"><i class="mdi mdi-cart-outline"> </i>    Корзина</a>
                </li>

                @if (User.Identity.IsAuthenticated)
                {
                    <li>
                        <a class="effect-underline" asp-controller="Order" asp-action="UserOrder" asp-route-userId="@((await UserManager.GetUserAsync(User)).Id)"><i class="mdi mdi-archive"></i> Минулі замовлення</a>
                    </li>

                    @if (User.IsInRole("Admin"))
                    {

                        <li class="dropdown-btn">
                            <a class="effect-underline" href="#"><i class="mdi mdi-account-supervisor-circle"> </i>   Admin</a>
                            <i class="fa fa-caret-down"></i>
                        </li>
                        <ul class=" dropdown-container">
                            <li><a class="effect-underline" asp-controller="Order" asp-action="AllOrders"><i class="mdi mdi-format-list-bulleted"></i> Усі замовлення</a></li>
                            <li><a class="effect-underline" asp-controller="MusicalInstrument" asp-action="ArchiveMusicalInstrument"><i class="mdi mdi-archive"></i>Архів товарів</a></li>
                            <li><a class="effect-underline" asp-controller="Roles" asp-action="UserList"><i class="mdi mdi-account-group"></i> Усі користувачі</a></li>
                            <li><a class="effect-underline" asp-controller="MICategory" asp-action="Index"><i class="mdi mdi-folder-multiple"></i> Усі категорії</a></li>
                            <li><a class="effect-underline" asp-controller="MICategory" asp-action="ArchiveCategory"><i class="mdi mdi-archive"></i>Архів категорій</a></li>
                            <li><a class="effect-underline" asp-controller="Roles" asp-action="Index"><i class="mdi mdi-account-key-outline"></i> Ролі</a></li>
                            <li><a class="effect-underline" asp-controller="MusicalInstrument" asp-action="Create"><i class="mdi mdi-plus-box"></i> Додати товар</a></li>
                            <li><a class="effect-underline" asp-controller="MICategory" asp-action="Add"><i class="mdi mdi-clipboard-plus"></i> Додати категорію</a></li>
                        </ul>

                    }

                }


            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->

        <nav id="navbar" class="navbar navbar-expand-lg shadow-lg">

            <button type="submit" class="btn btn-inverse-danger btn-icon">
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"> <i class="mdi mdi-sort-variant"></i></a>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-4">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="effect-underline nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout (@User.Identity.Name)</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="effect-underline nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="effect-underline nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    }

                </ul>
            </div>
        </nav>
        <div id="page-content-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <script src="~/js/bootstrap.min.js"></script>сс
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script>

        //* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }


        $(window).on('load', function () {
            $(".loader").fadeOut(1000);
            $(".content").fadeIn(1000);
        });
    </script>
    <script>

        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

    </script>
</body>
</html>